language: rust
before_install:
  - curl -sS https://static.rust-lang.org/rustup.sh > rustup.sh
  - chmod +x ./rustup.sh
  - ./rustup.sh --yes
install:
  - rustup install nightly
script: 
  - make build
  - make test
