language: rust
sudo: required
dist: trusty
env:
  - PATH=$PATH:$HOME/.cargo/bin
install:
  - curl -sSf https://sh.rustup.rs | sh -s -- -y
  - rustup install nightly
matrix:
  allow_failures:
    - rust: nightly
script:
  - make build
  - make test
