language: rust
env:
  - PATH=$PATH:$HOME/.cargo/bin
matrix:
  allow_failures:
    - rust: nightly
install:
  - curl -sSf https://sh.rustup.rs | sh -s -- -y
  - rustup install nightly
script:
  - make build
  - make test
