language: rust
before_install:
  - sudo curl -sS https://static.rust-lang.org/rustup.sh > rustup.sh
  - sudo chmod +x ./rustup.sh
  - sudo ./rustup.sh --yes
install:
  - rustup install nightly
script: 
  - make build
  - make test
