[package]
name = "bert"
version = "0.1.0"
authors = ["Valeryi Savich <Relrin78@gmail.com>"]

[dependencies]
byteorder = "0.5.3"
serde = "0.8.6"
num = "0.1.34"

[dev-dependencies]
serde_macros = "0.8.*"
